"""empty message

Revision ID: 732b8ea45006
Revises: 35701d828d45
Create Date: 2023-06-05 11:19:25.301771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732b8ea45006'
down_revision = '35701d828d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
